//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetM8.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class room
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public room()
        {
            this.userrooms = new HashSet<userroom>();
            this.leagues = new HashSet<league>();
        }
    
        public int idRoom { get; set; }
        public string name { get; set; }
        public sbyte visibility { get; set; }
        public int distributionType { get; set; }
        public int scoringType { get; set; }
        public int sport { get; set; }
        public int minPlayers { get; set; }
        public int maxPlayers { get; set; }
        public int bet { get; set; }
        public System.DateTime dateBegin { get; set; }
        public System.DateTime dateEnd { get; set; }
        public System.DateTime dateCancel { get; set; }
        public int admin { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<userroom> userrooms { get; set; }
        public virtual user user { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<league> leagues { get; set; }
    }
}
