-- MySQL Script generated by MySQL Workbench
-- Mon May  6 20:14:52 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_betm8
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_betm8
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_betm8` DEFAULT CHARACTER SET utf8 ;
USE `db_betm8` ;

-- -----------------------------------------------------
-- Table `db_betm8`.`Korisnik`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_betm8`.`Korisnik` (
  `idKorisnik` INT NOT NULL AUTO_INCREMENT,
  `Ime` VARCHAR(20) NOT NULL,
  `Prezime` VARCHAR(20) NOT NULL,
  `KorisnickoIme` VARCHAR(20) NOT NULL,
  `Sifra` VARCHAR(40) NOT NULL,
  `Email` VARCHAR(40) NOT NULL,
  `Zemlja` VARCHAR(30) NOT NULL,
  `Tip` INT NOT NULL,
  `Pare` INT NOT NULL,
  `Status` INT NOT NULL,
  PRIMARY KEY (`idKorisnik`),
  UNIQUE INDEX `KorisnickoIme_UNIQUE` (`KorisnickoIme` ASC) VISIBLE,
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_betm8`.`Soba`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_betm8`.`Soba` (
  `idSoba` INT NOT NULL AUTO_INCREMENT,
  `Ime` VARCHAR(20) NOT NULL,
  `Vidljivost` TINYINT NOT NULL,
  `NacinRaspodele` INT NOT NULL,
  `NacinBodovanja` INT NOT NULL,
  `Sport` INT NOT NULL,
  `MinBrIgraca` INT NOT NULL,
  `MaxBrIgraca` INT NOT NULL,
  `Ulog` INT NOT NULL,
  `DatumPocetka` DATETIME NOT NULL,
  `DatumKraja` DATETIME NOT NULL,
  `PoslednjiDanZaOdustajanje` DATETIME NOT NULL,
  `Admin` INT NOT NULL,
  PRIMARY KEY (`idSoba`),
  INDEX `fk_Soba_Korisnik1_idx` (`Admin` ASC) VISIBLE,
  CONSTRAINT `fk_Soba_Korisnik1`
    FOREIGN KEY (`Admin`)
    REFERENCES `db_betm8`.`Korisnik` (`idKorisnik`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_betm8`.`KorisnikSoba`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_betm8`.`KorisnikSoba` (
  `idKorisnik` INT NOT NULL,
  `idSoba` INT NOT NULL,
  `Poeni` INT NOT NULL,
  PRIMARY KEY (`idKorisnik`, `idSoba`),
  INDEX `fk_Korisnik_has_Soba_Soba1_idx` (`idSoba` ASC) VISIBLE,
  INDEX `fk_Korisnik_has_Soba_Korisnik_idx` (`idKorisnik` ASC) VISIBLE,
  CONSTRAINT `fk_Korisnik_has_Soba_Korisnik`
    FOREIGN KEY (`idKorisnik`)
    REFERENCES `db_betm8`.`Korisnik` (`idKorisnik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Korisnik_has_Soba_Soba1`
    FOREIGN KEY (`idSoba`)
    REFERENCES `db_betm8`.`Soba` (`idSoba`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_betm8`.`Liga`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_betm8`.`Liga` (
  `idLiga` INT NOT NULL AUTO_INCREMENT,
  `Ime` VARCHAR(20) NOT NULL,
  `Sport` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idLiga`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_betm8`.`Utakmica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_betm8`.`Utakmica` (
  `idUtakmica` INT NOT NULL AUTO_INCREMENT,
  `Tim1` VARCHAR(20) NOT NULL,
  `Tim2` VARCHAR(20) NOT NULL,
  `idLiga` INT NOT NULL,
  PRIMARY KEY (`idUtakmica`),
  INDEX `fk_Utakmica_Liga1_idx` (`idLiga` ASC) VISIBLE,
  CONSTRAINT `fk_Utakmica_Liga1`
    FOREIGN KEY (`idLiga`)
    REFERENCES `db_betm8`.`Liga` (`idLiga`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_betm8`.`Predikcija`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_betm8`.`Predikcija` (
  `idPredikcija` INT NOT NULL AUTO_INCREMENT,
  `Prognoza` CHAR(1) NOT NULL,
  `idUtakmica` INT NOT NULL,
  `idKorisnik` INT NOT NULL,
  `idSoba` INT NOT NULL,
  PRIMARY KEY (`idPredikcija`),
  INDEX `fk_Predikcija_Utakmica1_idx` (`idUtakmica` ASC) VISIBLE,
  INDEX `fk_Predikcija_KorisnikSoba1_idx` (`idKorisnik` ASC, `idSoba` ASC) VISIBLE,
  CONSTRAINT `fk_Predikcija_Utakmica1`
    FOREIGN KEY (`idUtakmica`)
    REFERENCES `db_betm8`.`Utakmica` (`idUtakmica`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Predikcija_KorisnikSoba1`
    FOREIGN KEY (`idKorisnik` , `idSoba`)
    REFERENCES `db_betm8`.`KorisnikSoba` (`idKorisnik` , `idSoba`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_betm8`.`SobaLiga`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_betm8`.`SobaLiga` (
  `idLiga` INT NOT NULL,
  `idSoba` INT NOT NULL,
  PRIMARY KEY (`idLiga`, `idSoba`),
  INDEX `fk_Liga_has_Soba_Soba1_idx` (`idSoba` ASC) VISIBLE,
  INDEX `fk_Liga_has_Soba_Liga1_idx` (`idLiga` ASC) VISIBLE,
  CONSTRAINT `fk_Liga_has_Soba_Liga1`
    FOREIGN KEY (`idLiga`)
    REFERENCES `db_betm8`.`Liga` (`idLiga`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Liga_has_Soba_Soba1`
    FOREIGN KEY (`idSoba`)
    REFERENCES `db_betm8`.`Soba` (`idSoba`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
