//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetM8.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_betm8Entities1 : DbContext
    {
        public db_betm8Entities1()
            : base("name=db_betm8Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<game> games { get; set; }
        public virtual DbSet<league> leagues { get; set; }
        public virtual DbSet<prediction> predictions { get; set; }
        public virtual DbSet<room> rooms { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<userroom> userrooms { get; set; }
    }
}
