//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetM8.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class userroom
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public userroom()
        {
            this.predictions = new HashSet<prediction>();
        }
    
        public int idUser { get; set; }
        public int idRoom { get; set; }
        public int points { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prediction> predictions { get; set; }
        public virtual room room { get; set; }
        public virtual user user { get; set; }
    }
}
